learning_templates/basic_template_app/urls.py
from django.conf.urls import url
from basic_template_app import views

# Template Tagg
# This name 'basic_template_app' is used inside html
app_name = 'basic_template_app'

urlpatterns = [

    url(r'^relative/$',views.relative, name = 'relative'),
    url(r'^other/$',views.other, name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from basic_template_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index , name = 'index'),
    url(r'^basic_template_app/',include('basic_template_app.urls')),
]

learning_templates/basic_template_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_template_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'name':'Hello Filter','Number':540}
    return render(request,'basic_template_app/index.html',context_dict)

def other(request):
    return render(request,'basic_template_app/other.html')

def relative(request):
    return render(request,'basic_template_app/relative_template_url.html')

learning_templates/templates/basic_template_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Bootstrap link  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous"> -->

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_template_app:other'%}">Other</a></li>
        </ul>
      </div>

    </nav>

    <div class="container">

      {% block body_block %}

        <!-- Anything outside this block in inhereted -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_template_app/index.html
<!DOCTYPE html>
{% extends "basic_template_app/base.html" %}
{% block body_block %}
<h1>Im Index Page</h1>
<h2>This is Template inhereted</h2>

      <!-- Template Filter -->
        <h1>{{name}}</h1>

        <!-- Make every letter capital , using predefined function upper -->
        <h3>{{name|upper}}</h3>

        <!-- Using Custom filter -->

        <h1>{{ name|cut:'Hello'}}</h1>

        <h2>{{Number}}</h2>

        <!-- Adding 5 to the given number by passing value -->
        <h2>{{Number|add:5}}</h2>

{% endblock%}

learning_templates/templates/basic_template_app/other.html
<!DOCTYPE html>
{% extends "basic_template_app/base.html" %}

<!-- Anything inside is printed here -->
{% block body_block %}
<h1>I m Other</h1>
<h2>Anything inside block is printed here ......Template inhereted</h2>
{% endblock %}

learning_templates/templates/basic_template_app/relative_template_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome To Relative Template URL</h1>
    <a href="{% url 'basic_template_app:other' %}">Go To Other Page</a>
    <p></p>
    <a href="{% url 'admin:index' %}">Go To Admin Page</a>
    <p></p>
<a href="{% url 'index' %}">Go To Index</a>

  </body>
</html>